name: Dynamic README injection
on: 
  schedule:
    - cron: "0 * * * *"

jobs:
  get-inspirational-quotes:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Let the magic happen
        uses: actions/setup-node@v1
        with: 
          node-version: 16.13.1

      - run: yarn

      - run: node .

      - name: Add to github repo
        run: |
          git config pull.rebase false
          git pull
          git add .
          git config --global user.name "Your Name"
          git config --global user.email "Your E-Mail"
          git commit -m "[Automated README updated with new Inspirational Quote!"
      - name: Push
        uses: ad-m/github-push-action@master
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}